version: '2'

services:
  app:
    container_name: app
    image: 'docker-spring-boot-postgres:latest'
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgresAdmin
      - SPRING_DATASOURCE_USERNAME=hoanghuyvuxh1
      - SPRING_DATASOURCE_PASSWORD=123456789
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db


  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=hoanghuyvuxh1
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=postgresAdmin
    volumes:
      - db-data:/var/lib/postgressql/data
    ports:
      - "5432:5432"

  pg-admin:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=vhong10092001@email.com
        - PGADMIN_DEFAULT_PASSWORD=123456789
      ports:
        - "8889:80"

volumes:
  db-data:
